### ISSUE TITLE
add piciture

### ISSUE THREAD

**Issue by xiaqinwen11** [adnguyen/Hahn_lab_protocols#2]
![img_1652](https://user-images.githubusercontent.com/31771163/34692931-e3de4e2c-f48f-11e7-8b48-0af6eb84753d.JPG)

**Comment by dahahn** [comment]
Pictures of Soxhlet apparatus
![soxhletpic1](https://user-images.githubusercontent.com/4992153/34693770-df28f0dc-f492-11e7-8683-1bc7d3070558.png)

**Comment by dahahn** [comment]
Soxhlet Picture 2
![soxhletapppic2](https://user-images.githubusercontent.com/4992153/34693858-241654e6-f493-11e7-9866-3969537adf46.png)

**Comment by dahahn** [comment]
Soxhlet chamber picture
![soxhletpic3](https://user-images.githubusercontent.com/4992153/34693878-33894406-f493-11e7-9e1d-ec82464558e5.png)

**Comment by dahahn** [comment]
Soxhlet stand picture
![soxhletstandpic](https://user-images.githubusercontent.com/4992153/34693904-41f6958e-f493-11e7-879d-8c995927905b.png)
